### PR TITLE
build: fix for the misuse of IDF_VER 

### PR DESCRIPTION
**Pull request by huming2207**
See: https://github.com/joltwallet/esp_littlefs/issues/125

### CODE REVIEW

**Comment by huming2207** [comment]
Hmm this is weird, I think it suppose to work as expected. Let me try logging the `IDF_VER_NO_V` and see what's the behaviour in ESP-IDF 4.2. 

Meanwhile I don't have the environment set up for 4.2 locally so I will amend the commit in this PR and let the CI does the test for me.

**Comment by huming2207** [comment]
I think I fixed it. The original cmake file's version detection logic is wrong: https://github.com/joltwallet/esp_littlefs/blob/5a375263fb07219d2a3748fc43067803754c7c67/project_include.cmake#L52

Change the `VERSION_GREATER` to `VERSION_GREATER_EQUAL` fixes the issue.

**Comment by huming2207** [comment]
See this CI result: https://github.com/huming2207/esp_littlefs/actions/runs/5063107970/jobs/9089346490

**Comment by huming2207** [comment]
Anyway, problem resolved, please review again. Thanks!

**Comment by BrianPugh** [comment]
excellent! thank you so much! will be merging and releasing momentarily.

**Comment by BrianPugh** [comment]
included in v1.5.5

**Pull request merged**
