### PR TITLE
Add support for mutliple backends

### PR DESCRIPTION
**Pull request by raldone01**
I don't expect this pull request to get merged as the code changes are very drastic. The sdcard and ram backends are poorly tested. The sdcard backend should work though.

I really just want to show you what I have done. Your vfs abstraction really sped things up. Thanks for your work.

If you want add support for multiple backends you may be able to use some of my code in the future.

### CODE REVIEW

**Comment by BrianPugh** [comment]
this is quite the PR. I've only skimmed it, I'll try and give it a thorough read when i have more time. Thank you for contributing!

**Comment by raldone01** [comment]
The first merge should be fine but it was a mistake using the github desktop app for the first time. I added another commit to the pull request which adds a config option to allow unlink to also delete empty directories which is required if someone wants to use the ghc::filesystem on top of this as it only calls the remove function to delete folders and files. The std::filesystem is not yet functional even when the cpp17 flag is used.

**Comment by BrianPugh** [comment]
I'm going to close this PR; it was a very cool contribution, but also quite large. To me, this was more of [a puppy than a cake](https://textual.textualize.io/blog/2023/07/29/pull-requests-are-cake-or-puppies/) 😄 .

We now have SD support due to #170, and I think that was the most requested by users.

**Comment by raldone01** [comment]
Understandable. SD support was the main reason for my changes. I actually think it's overcomplicated for what it does.

**Pull request closed without merging**
